version: '3'

services:
  soulrinha-compiler:
    build: .
    container_name: soulrinha
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '2G'
    volumes:
      - ./var/rinha:/var/rinha
